# Generated by Django 3.0 on 2020-06-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('user_choice', models.CharField(choices=[('0', 'Other'), ('1', 'Shopping'), ('2', 'Work '), ('3', 'Personal'), ('4', 'Grocery'), ('5', 'Assignment')], default='0', max_length=50)),
            ],
        ),
    ]
