# Generated by Django 3.0 on 2020-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('0', 'In Progress'), ('1', 'Compeleted')], default='0', max_length=50),
        ),
    ]
